const C=require('../contracts');
class MemoryStorage{constructor(){this.m=new Map()}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,v)}}
class ProfileForwardEngine{
 constructor({storage,configs,limit=10000,expiryMs=72*3600e3}={}){this.storage=storage||new MemoryStorage();this.configs=configs||{};this.limit=limit;this.expiryMs=expiryMs;this.key='profile-forward-trades-v1'}
 list(){try{const x=JSON.parse(this.storage.getItem(this.key)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
 save(a){const open=a.filter(x=>x.status==='OPEN'),closed=a.filter(x=>x.status!=='OPEN');const keep=[...closed.slice(-Math.max(0,this.limit-open.length)),...open];this.storage.setItem(this.key,JSON.stringify(keep));return true}
 record(profiles,result,market,view){if(!market?.globalForex?.isOpen||view?.isHistorical||result?.analysisMode!=='MULTI_TF_EXECUTION')return{created:0,reason:'GATE_BLOCKED'};const plan=C.validateTradePlan({...result.tradePlan,direction:result.direction});if(!plan.valid)return{created:0,reason:'CONTRACT_INVALID',errors:plan.errors};const {entry,sl,tp1}=plan.value,a=this.list(),stamp=String(view.asOf||view.points?.at(-1)?.t),h1Close=String(view.h1Bars?.at(-1)?.t||stamp);let created=0;for(const x of Object.values(profiles||{})){if(!['BUY','SELL'].includes(x.direction)||x.direction!==result.direction)continue;const cfg=this.configs[x.code];if(!cfg)continue;const signalKey=`${x.code}|${cfg.version}|${h1Close}|${x.direction}`;if(a.some(t=>t.signalKey===signalKey))continue;const risk=Math.abs(entry-sl),trade={id:`${stamp}|${x.code}|${cfg.version}|${x.direction}`,signalKey,profileCode:x.code,profileVersion:cfg.version,direction:x.direction,entry,sl,risk,tp1,tp1R:Math.abs(tp1-entry)/risk,status:'OPEN',result:null,realizedR:null,openedAt:stamp,closedAt:null,resolution:null};const vr=C.validateProfileForwardTrade(trade);if(!vr.valid)continue;a.push(trade);created++}if(created)this.save(a);return{created,reason:created?'CREATED':'NO_ELIGIBLE_PROFILE'}}
 update(points,market,view){if(!market?.globalForex?.isOpen||view?.isHistorical)return 0;const a=this.list();let changed=0;for(const x of a.filter(t=>t.status==='OPEN')){for(const b of points.filter(b=>Date.parse(b.t)>Date.parse(x.openedAt)).sort((a,b)=>Date.parse(a.t)-Date.parse(b.t))){const hitSL=x.direction==='BUY'?b.l<=x.sl:b.h>=x.sl,hitTP=x.direction==='BUY'?b.h>=x.tp1:b.l<=x.tp1;if(hitSL&&hitTP){Object.assign(x,{status:'AMBIGUOUS',closedAt:b.t,resolution:'BOTH_HIT_SAME_M5'});changed++;break}if(hitSL){Object.assign(x,{status:'SL',result:'LOSS',realizedR:-1,closedAt:b.t,resolution:'SL_HIT'});changed++;break}if(hitTP){Object.assign(x,{status:'TP1',result:'WIN',realizedR:x.tp1R,closedAt:b.t,resolution:'TP1_HIT'});changed++;break}if(Date.parse(b.t)-Date.parse(x.openedAt)>=this.expiryMs){Object.assign(x,{status:'EXPIRED',closedAt:b.t,resolution:'72H_EXPIRED'});changed++;break}}}if(changed)this.save(a);return changed}
 stats(){const order=['STD_STRUCTURE','EMA_TREND','RSI_MOMENTUM','MACD_MOMENTUM'],a=this.list();return order.map(code=>{const z=a.filter(x=>x.profileCode===code),wins=z.filter(x=>x.result==='WIN').length,losses=z.filter(x=>x.result==='LOSS').length,closed=wins+losses,rs=z.filter(x=>Number.isFinite(x.realizedR)).map(x=>x.realizedR);return{code,total:z.length,open:z.filter(x=>x.status==='OPEN').length,closed,wins,losses,ambiguous:z.filter(x=>x.status==='AMBIGUOUS').length,expired:z.filter(x=>x.status==='EXPIRED').length,winRate:closed?Number((wins/closed*100).toFixed(1)):null,avgR:rs.length?Number((rs.reduce((n,v)=>n+v,0)/rs.length).toFixed(2)):null}})}
}
module.exports={ProfileForwardEngine,MemoryStorage};
