(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TradeLabContracts=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const finite=v=>Number.isFinite(Number(v));
const iso=v=>typeof v==='string'&&Number.isFinite(Date.parse(v));
const result=(errors,value)=>({valid:errors.length===0,errors,value});
function validateCandle(x){const e=[];if(!x||typeof x!=='object')return result(['CANDLE_OBJECT_REQUIRED'],x);if(!iso(x.t))e.push('CANDLE_TIME_INVALID');for(const k of ['o','h','l','c'])if(!finite(x[k]))e.push(`CANDLE_${k.toUpperCase()}_INVALID`);if(e.length===0){const o=+x.o,h=+x.h,l=+x.l,c=+x.c;if(h<Math.max(o,c,l))e.push('CANDLE_HIGH_GEOMETRY');if(l>Math.min(o,c,h))e.push('CANDLE_LOW_GEOMETRY')}return result(e,x)}
function validateCandleSeries(a,{requireClosed=false}={}){const e=[];if(!Array.isArray(a)||!a.length)return result(['CANDLE_SERIES_REQUIRED'],a);let prior=-Infinity;const seen=new Set();a.forEach((x,i)=>{const r=validateCandle(x);r.errors.forEach(v=>e.push(`${i}:${v}`));const t=Date.parse(x?.t);if(Number.isFinite(t)){if(t<=prior)e.push(`${i}:CANDLE_TIME_NOT_ASCENDING`);if(seen.has(t))e.push(`${i}:CANDLE_TIME_DUPLICATE`);seen.add(t);prior=t}if(requireClosed&&x?.closed!==true)e.push(`${i}:CANDLE_NOT_CLOSED`)});return result(e,a)}
function validateTradePlan(p){const e=[];if(!p||typeof p!=='object')return result(['TRADE_PLAN_REQUIRED'],p);if(p.valid!==true)e.push('TRADE_PLAN_NOT_VALID');if(!['BUY','SELL'].includes(p.direction))e.push('TRADE_DIRECTION_INVALID');const entry=Number(p.entry?.price),sl=Number(p.sl?.price),tp1=Number(p.targets?.[0]?.price);if(!finite(entry))e.push('ENTRY_PRICE_INVALID');if(!finite(sl))e.push('SL_PRICE_INVALID');if(!finite(tp1))e.push('TP1_PRICE_INVALID');if(e.length===0){if(p.direction==='BUY'&&!(sl<entry&&entry<tp1))e.push('BUY_GEOMETRY_INVALID');if(p.direction==='SELL'&&!(tp1<entry&&entry<sl))e.push('SELL_GEOMETRY_INVALID')}return result(e,{entry,sl,tp1,direction:p.direction})}
function validateProfileDecision(x){const e=[];if(!x||typeof x!=='object')return result(['PROFILE_DECISION_REQUIRED'],x);if(!['STD_STRUCTURE','EMA_TREND','RSI_MOMENTUM','MACD_MOMENTUM'].includes(x.code))e.push('PROFILE_CODE_INVALID');if(typeof x.version!=='string'||!x.version)e.push('PROFILE_VERSION_INVALID');if(!['BUY','SELL','WAIT'].includes(x.direction))e.push('PROFILE_DIRECTION_INVALID');return result(e,x)}
function validateProfileForwardTrade(x){const e=[];if(!x||typeof x!=='object')return result(['PROFILE_TRADE_REQUIRED'],x);for(const k of ['id','signalKey','profileCode','profileVersion','openedAt'])if(typeof x[k]!=='string'||!x[k])e.push(`${k.toUpperCase()}_INVALID`);if(!['BUY','SELL'].includes(x.direction))e.push('DIRECTION_INVALID');for(const k of ['entry','sl','risk','tp1','tp1R'])if(!finite(x[k]))e.push(`${k.toUpperCase()}_INVALID`);if(!['OPEN','TP1','SL','AMBIGUOUS','EXPIRED','INVALID'].includes(x.status))e.push('STATUS_INVALID');return result(e,x)}
return{validateCandle,validateCandleSeries,validateTradePlan,validateProfileDecision,validateProfileForwardTrade};
});
